### ISSUE TITLE
Find prospective members

### ISSUE THREAD

**Issue by cmilkaitis** [starboardcoop/things-app#14]

**Comment by dillonfagan** [comment]
I guess this is when we really start sharing it around.

- [ ] Twitter
- [ ] Reddit
- [ ] LinkedIn
- [ ] Facebook?
- [ ] Posters? (e.g. @ Urban Greens)

**Comment by dillonfagan** [comment]
When should we consider this closed?

**Comment by dillonfagan** [comment]
I'm gonna go out on a limb and call this task done. We now have 50+ prospective members...
