### ISSUE TITLE
Searching by Categories

### ISSUE THREAD

**Issue by mdantuono** [starboardcoop/things-app#157]
Do we want a row of buttons to filter? Or do we want clickable list of categories and it takes you there on the page.

**Comment by dillonfagan** [comment]
How about a drop-down chooser?

**Comment by dillonfagan** [comment]
<img width="446" alt="Screen Shot 2022-07-11 at 8 13 28 PM" src="https://user-images.githubusercontent.com/5107025/178379530-3894fd56-bd1d-4455-a77c-ab1df9d5cf33.png">

**Comment by dillonfagan** [comment]
<img width="266" alt="Screen Shot 2022-07-11 at 8 22 02 PM" src="https://user-images.githubusercontent.com/5107025/178380374-4e543a8a-ef41-4375-8006-79c4e5977c15.png">
