### ISSUE TITLE
Show where items are stocked

### ISSUE THREAD

**Issue by dillonfagan** [starboardcoop/things-app#181]
Instead of saying "X in stock", I would like these indicators to say "X @ PPL" or "X in Stock" if the Thing is not at PPL. Some Things will need to have multiple indicators if there are some units in different locations.

**Comment by cmilkaitis** [comment]
API route exists. App is configured to get the PPL inventory from the Inventory base on airtable.
Current problem exists with the Thing name being a link within airtable rather than a single line of text.
