### ISSUE TITLE
Calendar Reservations for Things

### ISSUE THREAD

**Issue by cmilkaitis** [starboardcoop/things-app#59]
How could a user select an item to reserve for a specific date with a return date.

**Comment by cmilkaitis** [comment]
should and must because it does need some sort of reservation system but doesnt necessarily need to be a calendar

**Comment by dillonfagan** [comment]
Not saying we should do this, but it _could_ be possible to do without a digital reservation system at first. A member could use the app to see what is available and then call to reserve. It would obviously be less convenient, but it's an option, depending on our time constraints.

**Comment by mdantuono** [comment]
- [ ] #74 
- [ ] #76

**Comment by dillonfagan** [comment]
It was discussed in PVD Things meetings with Devon that we should not offer reservations, because this usually turns into a mess where desirable tools are never available
